### PR TITLE
update to recent pyarrow

### PR DESCRIPTION
**Pull request by johannct**
change write_gcr_to_parquet.py so that 2 arguments now obsolete to drive pyarrow are removed

### CODE REVIEW

**Comment by wmwv** [comment]
> now obsolete to drive pyarrow

I don't think I quite follow this.  What do you mean by "obsolete"?

**Comment by wmwv** [comment]
Do you mean:

**Comment by heather999** [comment]
@wmwv I think the issue was that our use of append was not compatible with the "newer" pyarrow 0.13.0 that DM now provides as part of its distribution:  #381

**Comment by wmwv** [comment]
@johannct Do you need anything further to merge this?

**Pull request merged**
