### PR TITLE
Add `--filters` CLI option to `make_object_catalog.py`

### PR DESCRIPTION
**Pull request by yymao**
This PR adds the `--filters` CLI option to `make_object_catalog.py` to support non-ugrizy filter sets. There are several way to specify this option: 

- `--filters=hsc`  (use the hsc preset)
- `--filters=chft`  (use the chft preset)
- `--filters=ugrizy`  (if all filters have single-character names)
- `--filters=u,g,r,i,z,y,w1,w2`  (comma-separated filter names)

This PR is to make @boutigny's hot fix in 585a1f2 an actual user option.

### CODE REVIEW

**Comment by wmwv** [comment]
@yymao @boutigny  Is this PR still relevant?

**Comment by boutigny** [comment]
As far as I know this is still relevant.

**Comment by wmwv** [comment]
@boutigny Very good.  Did you get a chance to test this PR?
It's based on your previous hack.  We'd like to make sure that this implementation still works for you.

**Comment by boutigny** [comment]
I think I tested it (not sure unfortunately) and it is difficult for me to retest it now. I suggest accepting the PR

**Comment by wmwv** [comment]
@boutigny
Very good.  Merged.

**Pull request merged**
