### PR TITLE
initial guess at some package versions for Run 2.0i

### PR DESCRIPTION
**Pull request by jchiang87**

### CODE REVIEW

**Comment by jbkalmbach** [comment]
`Twinkles` still requires an update once the final `cosmoDC2` galaxies are ready.

**Comment by yymao** [comment]
@danielsf @jchiang87 are we still planning on going into production tomorrow? And if yes, should I tag `gcr-catalogs` even though there's still unfinished work, or are you planning to just use the master branch for instance catalog generation?

**Comment by jchiang87** [comment]
We are planning to go into production tomorrow, but I'm not sure which `gcr-catalogs` will be, are being, or have been used.

**Comment by danielsf** [comment]
InstanceCatalog production is going to start (if there is any justice in the Universe) in a few hours

we will just use master

**Comment by yymao** [comment]
Okay, just note the commit hash that you use...

**Comment by rmjarvis** [comment]
I'd recommend tagging with something like `lsst.dc2.0a` or something.  Makes it easier to find later rather than just some random SHA.  (Although you can tag after the fact if you start production with the current master at the time.)

**Comment by yymao** [comment]
I've tagged `gcr-catalogs` at [v0.9.0](https://github.com/LSSTDESC/gcr-catalogs/releases/tag/v0.9.0) in case people want to use a tagged version for production.

**Comment by wmwv** [comment]
@jchiang87 I propose closing this PR without further action.  Do you agree?

**Comment by jchiang87** [comment]
sure.  closing now.

**Pull request closed without merging**
